[2024-09-02T15:49:07.935+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T15:49:07.954+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ranking_news.scrape_data scheduled__2024-09-01T00:00:00+00:00 [queued]>
[2024-09-02T15:49:07.966+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ranking_news.scrape_data scheduled__2024-09-01T00:00:00+00:00 [queued]>
[2024-09-02T15:49:07.967+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-02T15:49:07.984+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): scrape_data> on 2024-09-01 00:00:00+00:00
[2024-09-02T15:49:07.999+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=86) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-02T15:49:08.002+0000] {standard_task_runner.py:72} INFO - Started process 91 to run task
[2024-09-02T15:49:08.002+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ranking_news', 'scrape_data', 'scheduled__2024-09-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/crawler_dag.py', '--cfg-path', '/tmp/tmpnze_yi4u']
[2024-09-02T15:49:08.004+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask scrape_data
[2024-09-02T15:49:08.066+0000] {task_command.py:467} INFO - Running <TaskInstance: ranking_news.scrape_data scheduled__2024-09-01T00:00:00+00:00 [running]> on host 1c4de405e3fc
[2024-09-02T15:49:08.141+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ranking_news' AIRFLOW_CTX_TASK_ID='scrape_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-01T00:00:00+00:00'
[2024-09-02T15:49:08.143+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-02T15:49:08.144+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-02T15:49:08.145+0000] {logging_mixin.py:190} INFO - Current task name:scrape_data state:running start_date:2024-09-02 15:49:07.955639+00:00
[2024-09-02T15:49:08.145+0000] {logging_mixin.py:190} INFO - Dag name:ranking_news and current dag run status:running
[2024-09-02T15:49:08.146+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T15:49:54.934+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawler_func.py", line 46, in scrape
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.cache/selenium/chromedriver/linux64/128.0.6613.86/chromedriver unexpectedly exited. Status code was: 127

[2024-09-02T15:49:54.962+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-02T15:49:54.964+0000] {logging_mixin.py:190} INFO - Task start:2024-09-02 15:49:07.955639+00:00 end:2024-09-02 15:49:54.961347+00:00 duration:47.005708
[2024-09-02T15:49:54.965+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_data> dag:<DAG: ranking_news> dagrun:<DagRun ranking_news @ 2024-09-01 00:00:00+00:00: scheduled__2024-09-01T00:00:00+00:00, state:running, queued_at: 2024-09-02 15:49:05.286783+00:00. externally triggered: False>
[2024-09-02T15:49:54.965+0000] {logging_mixin.py:190} INFO - Failure caused by Message: Service /home/***/.cache/selenium/chromedriver/linux64/128.0.6613.86/chromedriver unexpectedly exited. Status code was: 127
[2024-09-02T15:49:54.966+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ranking_news, task_id=scrape_data, run_id=scheduled__2024-09-01T00:00:00+00:00, execution_date=20240901T000000, start_date=20240902T154907, end_date=20240902T154954
[2024-09-02T15:49:54.991+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T15:49:54.992+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task scrape_data (Message: Service /home/airflow/.cache/selenium/chromedriver/linux64/128.0.6613.86/chromedriver unexpectedly exited. Status code was: 127
; 91)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawler_func.py", line 46, in scrape
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.cache/selenium/chromedriver/linux64/128.0.6613.86/chromedriver unexpectedly exited. Status code was: 127

[2024-09-02T15:49:55.029+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-02T15:49:55.053+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-02T15:49:55.056+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
