[2024-09-02T16:41:14.381+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T16:41:14.397+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ranking_news.scrape_data manual__2024-09-02T16:31:39.923604+00:00 [queued]>
[2024-09-02T16:41:14.405+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ranking_news.scrape_data manual__2024-09-02T16:31:39.923604+00:00 [queued]>
[2024-09-02T16:41:14.406+0000] {taskinstance.py:2856} INFO - Starting attempt 4 of 4
[2024-09-02T16:41:14.419+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): scrape_data> on 2024-09-02 16:31:39.923604+00:00
[2024-09-02T16:41:14.424+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=177) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-02T16:41:14.426+0000] {standard_task_runner.py:72} INFO - Started process 180 to run task
[2024-09-02T16:41:14.426+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ranking_news', 'scrape_data', 'manual__2024-09-02T16:31:39.923604+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/crawler_dag.py', '--cfg-path', '/tmp/tmphf3y4fdd']
[2024-09-02T16:41:14.427+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask scrape_data
[2024-09-02T16:41:14.472+0000] {task_command.py:467} INFO - Running <TaskInstance: ranking_news.scrape_data manual__2024-09-02T16:31:39.923604+00:00 [running]> on host 5ee6e0b702c6
[2024-09-02T16:41:14.551+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ranking_news' AIRFLOW_CTX_TASK_ID='scrape_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T16:31:39.923604+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T16:31:39.923604+00:00'
[2024-09-02T16:41:14.552+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-02T16:41:14.553+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-02T16:41:14.553+0000] {logging_mixin.py:190} INFO - Current task name:scrape_data state:running start_date:2024-09-02 16:41:14.398714+00:00
[2024-09-02T16:41:14.554+0000] {logging_mixin.py:190} INFO - Dag name:ranking_news and current dag run status:running
[2024-09-02T16:41:14.555+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T16:41:14.556+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-09-02T16:41:14.661+0000] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2024-09-02T16:41:14.933+0000] {logger.py:11} INFO - Get LATEST chromedriver version for chromium
[2024-09-02T16:41:15.436+0000] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/128.0.6613.86/chromedriver-linux64/chromedriver] found in cache
[2024-09-02T16:41:15.606+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawler_func.py", line 49, in scrape
    driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5576b6a668da <unknown>
#1 0x5576b6734e50 <unknown>
#2 0x5576b676ce05 <unknown>
#3 0x5576b6768c78 <unknown>
#4 0x5576b67b564e <unknown>
#5 0x5576b67b4e66 <unknown>
#6 0x5576b67a9233 <unknown>
#7 0x5576b6777093 <unknown>
#8 0x5576b677809e <unknown>
#9 0x5576b6a2db3b <unknown>
#10 0x5576b6a31af1 <unknown>
#11 0x5576b6a19705 <unknown>
#12 0x5576b6a32662 <unknown>
#13 0x5576b69fe8df <unknown>
#14 0x5576b6a556d8 <unknown>
#15 0x5576b6a558a2 <unknown>
#16 0x5576b6a656cc <unknown>
#17 0x7f738975c144 <unknown>

[2024-09-02T16:41:15.620+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-02T16:41:15.621+0000] {logging_mixin.py:190} INFO - Task start:2024-09-02 16:41:14.398714+00:00 end:2024-09-02 16:41:15.620019+00:00 duration:1.221305
[2024-09-02T16:41:15.621+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_data> dag:<DAG: ranking_news> dagrun:<DagRun ranking_news @ 2024-09-02 16:31:39.923604+00:00: manual__2024-09-02T16:31:39.923604+00:00, state:running, queued_at: 2024-09-02 16:36:16.483975+00:00. externally triggered: True>
[2024-09-02T16:41:15.622+0000] {logging_mixin.py:190} INFO - Failure caused by Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5576b6a668da <unknown>
#1 0x5576b6734e50 <unknown>
#2 0x5576b676ce05 <unknown>
#3 0x5576b6768c78 <unknown>
#4 0x5576b67b564e <unknown>
#5 0x5576b67b4e66 <unknown>
#6 0x5576b67a9233 <unknown>
#7 0x5576b6777093 <unknown>
#8 0x5576b677809e <unknown>
#9 0x5576b6a2db3b <unknown>
#10 0x5576b6a31af1 <unknown>
#11 0x5576b6a19705 <unknown>
#12 0x5576b6a32662 <unknown>
#13 0x5576b69fe8df <unknown>
#14 0x5576b6a556d8 <unknown>
#15 0x5576b6a558a2 <unknown>
#16 0x5576b6a656cc <unknown>
#17 0x7f738975c144 <unknown>
[2024-09-02T16:41:15.622+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ranking_news, task_id=scrape_data, run_id=manual__2024-09-02T16:31:39.923604+00:00, execution_date=20240902T163139, start_date=20240902T164114, end_date=20240902T164115
[2024-09-02T16:41:15.636+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T16:41:15.637+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task scrape_data (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5576b6a668da <unknown>
#1 0x5576b6734e50 <unknown>
#2 0x5576b676ce05 <unknown>
#3 0x5576b6768c78 <unknown>
#4 0x5576b67b564e <unknown>
#5 0x5576b67b4e66 <unknown>
#6 0x5576b67a9233 <unknown>
#7 0x5576b6777093 <unknown>
#8 0x5576b677809e <unknown>
#9 0x5576b6a2db3b <unknown>
#10 0x5576b6a31af1 <unknown>
#11 0x5576b6a19705 <unknown>
#12 0x5576b6a32662 <unknown>
#13 0x5576b69fe8df <unknown>
#14 0x5576b6a556d8 <unknown>
#15 0x5576b6a558a2 <unknown>
#16 0x5576b6a656cc <unknown>
#17 0x7f738975c144 <unknown>
; 180)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawler_func.py", line 49, in scrape
    driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5576b6a668da <unknown>
#1 0x5576b6734e50 <unknown>
#2 0x5576b676ce05 <unknown>
#3 0x5576b6768c78 <unknown>
#4 0x5576b67b564e <unknown>
#5 0x5576b67b4e66 <unknown>
#6 0x5576b67a9233 <unknown>
#7 0x5576b6777093 <unknown>
#8 0x5576b677809e <unknown>
#9 0x5576b6a2db3b <unknown>
#10 0x5576b6a31af1 <unknown>
#11 0x5576b6a19705 <unknown>
#12 0x5576b6a32662 <unknown>
#13 0x5576b69fe8df <unknown>
#14 0x5576b6a556d8 <unknown>
#15 0x5576b6a558a2 <unknown>
#16 0x5576b6a656cc <unknown>
#17 0x7f738975c144 <unknown>

[2024-09-02T16:41:15.686+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-02T16:41:15.708+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-02T16:41:15.713+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
