[2024-09-02T15:57:41.340+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T15:57:41.359+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ranking_news.scrape_data manual__2024-09-02T15:49:04.585522+00:00 [queued]>
[2024-09-02T15:57:41.367+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ranking_news.scrape_data manual__2024-09-02T15:49:04.585522+00:00 [queued]>
[2024-09-02T15:57:41.367+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-09-02T15:57:41.384+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): scrape_data> on 2024-09-02 15:49:04.585522+00:00
[2024-09-02T15:57:41.392+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-02T15:57:41.394+0000] {standard_task_runner.py:72} INFO - Started process 71 to run task
[2024-09-02T15:57:41.395+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ranking_news', 'scrape_data', 'manual__2024-09-02T15:49:04.585522+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/crawler_dag.py', '--cfg-path', '/tmp/tmpulxqvumk']
[2024-09-02T15:57:41.397+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask scrape_data
[2024-09-02T15:57:41.467+0000] {task_command.py:467} INFO - Running <TaskInstance: ranking_news.scrape_data manual__2024-09-02T15:49:04.585522+00:00 [running]> on host 4e0093cd5802
[2024-09-02T15:57:41.565+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ranking_news' AIRFLOW_CTX_TASK_ID='scrape_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T15:49:04.585522+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T15:49:04.585522+00:00'
[2024-09-02T15:57:41.567+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-02T15:57:41.567+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-02T15:57:41.568+0000] {logging_mixin.py:190} INFO - Current task name:scrape_data state:running start_date:2024-09-02 15:57:41.360015+00:00
[2024-09-02T15:57:41.568+0000] {logging_mixin.py:190} INFO - Dag name:ranking_news and current dag run status:running
[2024-09-02T15:57:41.568+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T15:58:35.884+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawler_func.py", line 46, in scrape
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/airflow/.cache/selenium/chrome/linux64/128.0.6613.86/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55ee7f6a58da <unknown>
#1 0x55ee7f373e50 <unknown>
#2 0x55ee7f3abe05 <unknown>
#3 0x55ee7f3a7c78 <unknown>
#4 0x55ee7f3f464e <unknown>
#5 0x55ee7f3f3e66 <unknown>
#6 0x55ee7f3e8233 <unknown>
#7 0x55ee7f3b6093 <unknown>
#8 0x55ee7f3b709e <unknown>
#9 0x55ee7f66cb3b <unknown>
#10 0x55ee7f670af1 <unknown>
#11 0x55ee7f658705 <unknown>
#12 0x55ee7f671662 <unknown>
#13 0x55ee7f63d8df <unknown>
#14 0x55ee7f6946d8 <unknown>
#15 0x55ee7f6948a2 <unknown>
#16 0x55ee7f6a46cc <unknown>
#17 0x7fd17d190144 <unknown>

[2024-09-02T15:58:35.899+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-02T15:58:35.900+0000] {logging_mixin.py:190} INFO - Task start:2024-09-02 15:57:41.360015+00:00 end:2024-09-02 15:58:35.898946+00:00 duration:54.538931
[2024-09-02T15:58:35.900+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_data> dag:<DAG: ranking_news> dagrun:<DagRun ranking_news @ 2024-09-02 15:49:04.585522+00:00: manual__2024-09-02T15:49:04.585522+00:00, state:running, queued_at: 2024-09-02 15:49:04.624555+00:00. externally triggered: True>
[2024-09-02T15:58:35.901+0000] {logging_mixin.py:190} INFO - Failure caused by Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/***/.cache/selenium/chrome/linux64/128.0.6613.86/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55ee7f6a58da <unknown>
#1 0x55ee7f373e50 <unknown>
#2 0x55ee7f3abe05 <unknown>
#3 0x55ee7f3a7c78 <unknown>
#4 0x55ee7f3f464e <unknown>
#5 0x55ee7f3f3e66 <unknown>
#6 0x55ee7f3e8233 <unknown>
#7 0x55ee7f3b6093 <unknown>
#8 0x55ee7f3b709e <unknown>
#9 0x55ee7f66cb3b <unknown>
#10 0x55ee7f670af1 <unknown>
#11 0x55ee7f658705 <unknown>
#12 0x55ee7f671662 <unknown>
#13 0x55ee7f63d8df <unknown>
#14 0x55ee7f6946d8 <unknown>
#15 0x55ee7f6948a2 <unknown>
#16 0x55ee7f6a46cc <unknown>
#17 0x7fd17d190144 <unknown>
[2024-09-02T15:58:35.902+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ranking_news, task_id=scrape_data, run_id=manual__2024-09-02T15:49:04.585522+00:00, execution_date=20240902T154904, start_date=20240902T155741, end_date=20240902T155835
[2024-09-02T15:58:35.921+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T15:58:35.922+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task scrape_data (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/airflow/.cache/selenium/chrome/linux64/128.0.6613.86/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55ee7f6a58da <unknown>
#1 0x55ee7f373e50 <unknown>
#2 0x55ee7f3abe05 <unknown>
#3 0x55ee7f3a7c78 <unknown>
#4 0x55ee7f3f464e <unknown>
#5 0x55ee7f3f3e66 <unknown>
#6 0x55ee7f3e8233 <unknown>
#7 0x55ee7f3b6093 <unknown>
#8 0x55ee7f3b709e <unknown>
#9 0x55ee7f66cb3b <unknown>
#10 0x55ee7f670af1 <unknown>
#11 0x55ee7f658705 <unknown>
#12 0x55ee7f671662 <unknown>
#13 0x55ee7f63d8df <unknown>
#14 0x55ee7f6946d8 <unknown>
#15 0x55ee7f6948a2 <unknown>
#16 0x55ee7f6a46cc <unknown>
#17 0x7fd17d190144 <unknown>
; 71)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawler_func.py", line 46, in scrape
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/airflow/.cache/selenium/chrome/linux64/128.0.6613.86/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55ee7f6a58da <unknown>
#1 0x55ee7f373e50 <unknown>
#2 0x55ee7f3abe05 <unknown>
#3 0x55ee7f3a7c78 <unknown>
#4 0x55ee7f3f464e <unknown>
#5 0x55ee7f3f3e66 <unknown>
#6 0x55ee7f3e8233 <unknown>
#7 0x55ee7f3b6093 <unknown>
#8 0x55ee7f3b709e <unknown>
#9 0x55ee7f66cb3b <unknown>
#10 0x55ee7f670af1 <unknown>
#11 0x55ee7f658705 <unknown>
#12 0x55ee7f671662 <unknown>
#13 0x55ee7f63d8df <unknown>
#14 0x55ee7f6946d8 <unknown>
#15 0x55ee7f6948a2 <unknown>
#16 0x55ee7f6a46cc <unknown>
#17 0x7fd17d190144 <unknown>

[2024-09-02T15:58:35.959+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-02T15:58:35.982+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-02T15:58:35.992+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
